apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-api
  namespace: fcg-fase3
spec:
  replicas: 1
  selector:
    matchLabels: { app: users-api }
  template:
    metadata:
      labels: { app: users-api }
    spec:
      containers:
        - name: users-api
          image: fcg-users-api:fase3
          imagePullPolicy: IfNotPresent
          ports: [{ containerPort: 8080 }]
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ConnectionStrings__MongoDB
              value: "mongodb://admin:admin@mongodb:27017"
            - name: ConnectionStrings__Redis
              value: "redis:6379"
            - name: RabbitMQ__Host
              value: rabbitmq
          readinessProbe:
            httpGet: { path: /health, port: 8080 }
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: users-api
  namespace: fcg-fase3
spec:
  selector: { app: users-api }
  ports:
    - port: 8080
      targetPort: 8080
